server:
  port: 8888

spring:
  profiles:
    active: native
  application:
    name: config-service
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
  # ??? ???? ??
  cloud:
    config:
      server:
        git:
          uri: git@github.com:sup226/cloud-config-settings.git
          default-label: main
          # host-key는 SSH 프로토콜을 통해 Git 저장소에 접근할 때 Git 서버의 신뢰성을 검증하기 위해 제공한다.
          host-key: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQCj7ndNxQowgcQnjshcLrqPEiiphnt+VTTvDP6mHBL9j1aNUkY4Ue1gvwnGLVlOhGeYrnZaMgRK6+PKCUXaDbC7qtbW8gIkhL7aGCsOr/C56SJMy/BCZfxd1nWzAOxSDPgVsmerOBYfNqltV9/hWCqBywINIR+5dIg6JTJ72pcEpEjcYgXkE2YEFXV1JHnsKgbLWNlhScqb2UmyRkQyytRLtL+38TGxkxCflmO+5Z8CSSNY7GidjMIZ7Q4zMjA2n1nGrlTDkzwDCsw+wqFPGQA179cnfGWOWRVruj16z6XyvxvjJwbz0wQZ75XK5tKSb7FNyeIEs4TT4jk+S4dhPeAUC5y+bDYirYgM4GC7uEnztnZyaVWQ7B381AK4Qdrwt51ZqExKbQpTUNn+EjqoTwvqNj4kqx5QUCI0ThS/YkOxJCXmPUWZbhjpCg56i+2aB6CmK2JGhn57K5mj0MNdBXA4/WnwH6XoPWJzK5Nyu2zB3nAZp+S5hpQs+p1vN1/wsjk="
          host-key-algorithm: "ssh-rsa"
          private-key: |
            -----BEGIN EC PRIVATE KEY-----
            MHcCAQEEIL6v+6jtNhvb9Bx4ERPNk7AnjUMLLe3y/6sYDYT1PTgGoAoGCCqGSM49
            AwEHoUQDQgAEj3kyB0gB88zQ4kJ/5s+XfCa+k91NmBtmBCoMOB2CRiYFr+RDCAGJ
            8uA9s7vRDnyUDIhUkMY6yMNqJeeQwYwh/Q==
            -----END EC PRIVATE KEY-----

management:
  endpoints:
    web:
      exposure:
        include: refresh, health, beans, busrefresh
